package view;

import model.Event;
import service.Scheduler;

import javax.swing.DefaultListModel;
import java.util.Map;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.time.format.DateTimeFormatter;

public class SchedulePage extends javax.swing.JFrame {
    private final Scheduler sch;
    private DefaultListModel<String> dlmSchedule;
    
    // Konstruktor
    public SchedulePage(Scheduler sch) {
        this.sch = sch;
        initComponents();
        updateUser();
        
        dlmSchedule = new DefaultListModel<>();
        jListSchedule.setModel(dlmSchedule);
        
        viewSchedule();
        
    }

    // update nama user
    private void updateUser(){
        jLabel2.setText(sch.getUser().getName() + "'s schedule");
    }

    // Menampilkan schedule
    private void viewSchedule() {
        try {
            // Muat semua tim untuk mendapatkan nama tim
            Map<String, String> teamNames = sch.getTeamNames();

            // Load semua event
            for (Event e : sch.loadAllEvents()) {
                String teamLabel;
                if (e.isTeamEvent()) {
                    String teamId = e.getTeamId();
                    String teamName = teamNames.getOrDefault(teamId, "Unknown Team");
                    teamLabel = String.format("%s", teamName);
                } else {
                    teamLabel = "";
                }

                String jadwal = String.format("%s  %s  %s  %s",
                    e.getDate().format(DateTimeFormatter.ofPattern("yyyy-MM-dd")),
                    e.getTime().format(DateTimeFormatter.ofPattern("HH:mm")),
                    e.getTitle(), teamLabel);

                dlmSchedule.addElement(jadwal);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                    "Gagal memuat jadwal: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListSchedule = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListSchedule.setFont(new java.awt.Font("Hoefler Text", 0, 13)); // NOI18N
        jScrollPane1.setViewportView(jListSchedule);

        jLabel2.setFont(new java.awt.Font("Brush Script MT", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tsabita Syahida's Schedule");

        jButtonAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAdd.setText("Add Schedule");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Back to Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Herculanum", 0, 5)); // NOI18N
        jLabel3.setText("COPYRIGHT PBO_E_KEL6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButtonAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(27, 27, 27)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButtonAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        AddSchedulePage addSch = new AddSchedulePage(sch); 
        addSch.setVisible(true);
        dispose();
        
    }                                          

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        HomePage menu = new HomePage(sch); 
        menu.setVisible(true);  // buka halaman menu
        dispose();          
    }                                        

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jListSchedule;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}
