package view;

import service.Scheduler;

import java.io.IOException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class TeamPage extends javax.swing.JFrame {
    private final Scheduler sch;
    private DefaultListModel<String> dlmTeam;
    
    // Konstruktor
    public TeamPage(Scheduler sch) {
        this.sch = sch;
        initComponents();
        
        dlmTeam = new DefaultListModel<>();
        jListTim.setModel(dlmTeam);
        
        viewTeams();
    } 

    // Menampilkan tim
    private void viewTeams() {
        dlmTeam.clear(); // Kosongkan list sebelumnya
        try {
            List<String[]> teams = sch.getUserTeams();

            for (String[] team : teams) {
                String teamId = team[0];
                String teamName = team[1];
                dlmTeam.addElement(String.format("%s - %s", teamId, teamName));
            }

            if (dlmTeam.isEmpty()) {
                dlmTeam.addElement("(Tidak ada tim)");
            }

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                "Gagal memuat data tim: " + ex.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListTim = new javax.swing.JList<>();
        jButtonBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Your Team");

        jListTim.setFont(new java.awt.Font("Hoefler Text", 0, 13)); // NOI18N
        jScrollPane1.setViewportView(jListTim);

        jButtonBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBack.setText("Back to Home");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Herculanum", 0, 5)); // NOI18N
        jLabel4.setText("COPYRIGHT PBO_KEL6");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Add Team");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBack)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jButton1)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBack)
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        new AddTeamPage(sch).setVisible(true);
        dispose();
    }                                        

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        HomePage menu = new HomePage(sch); 
        menu.setVisible(true);  // buka halaman menu
        dispose();     
    }                                           

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jListTim;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}
